language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - $DEPLOY_TRIGGER_URL
    on_success: always
    on_failure: never
    on_start:   never
    on_cancel:  never
    on_error:   never